shopware_app_lifecycle:
    resource: '@ShopwareAppBundle/Resources/config/routing/lifecycle.xml'
    prefix:

shopware_app_webhook:
    resource: '@ShopwareAppBundle/Resources/config/routing/webhook.xml'
    prefix:

